border = '-' * 36
print('-'*17 + '\/' + '-'*17)
print('| '+ '   Welcome to the banana world   ' + '|')
print('-'*17 + '/\\' + '-'*17)
print('Hi, my name is Banana.\nI\'m not male nor female.\nLet\'s just say, I\'m Banana.\nOkay? :)')
print(border)
print('May I know your name?')
print('Note: Please insert your name')
name = input()
MC_name = name
print(border)
print('So, you\'re name is ' + MC_name + ', right?')
print('[1] Yes\n[2] No\nNote: Your may choose the answer \nby input the number on your screen')
answer = input()
choice = int(answer)
print(border)
while choice == 2:
    print('Oh well, what is your name then?')
    print('Note: Please insert your name')
    name = input()
    MC_name = name
    print(border)
    print('So, you are ' + MC_name + ', right?')
    print('[1] Yes\n[2] No')
    answer = input()
    choice = int(answer)
    print(border)
print('Welcome to Banana World, '+ MC_name + '!')
print('Say, do you like to learn more?')
print('The story beyond Banana World')
print('is yours to explore')
print('You may find this strange')
print('But here, the story would go advance')
print('Depending on your choices')
print(border)
